M48
; DRILL file {KiCad 8.0.8} date 2025-02-11T14:17:21-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-11T14:17:21-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X5.7251Y-5.1614
X6.0401Y-5.1614
T2
X5.32Y-3.05
X5.32Y-5.13
X6.5Y-3.05
X6.5Y-5.13
M30
